### ISSUE TITLE
It shows disconnected when PBE client is open.

### ISSUE THREAD

**Issue by tareqanwar** [OrangeNote/RuneBook#34] opened 2018-03-12 19:53 UTC
Is there any plan to support PBE client?

**Comment by OrangeNote** [comment] 2018-03-13 11:52
PBE should not differ from live client. In fact, PBE connection works fine on macOS.

But on Windows I found that there's an issue with the module I'm using for client connection: if you have PBE client and live client both installed in your machine, RuneBook tries to connect to `C:\\Riot Games\\League of Legends\\LeagueClient.exe` (it's the default path) and it fails. I'll double check if that's the cause and let you know. Thanks for asking!

**Comment by OrangeNote** [comment] 2018-03-20 06:28
I think this is solved now, but I need to fix #37 before closing.

**Comment by OrangeNote** [comment] 2018-03-20 13:53
So v1.5.1 should allow you to specify a path for different league installation in case RuneBook fails to recognize the currently open client. Please tell me if that's been solved and if you had to manually set the PBE path to make it work.

**Closed** 2018-07-12 11:48 UTC
